schema = 3

[mod]
  [mod."github.com/gdamore/encoding"]
    version = "v1.0.0"
    hash = "sha256-aV6wbQTwdOBHXMqWbhIxQ6YLun+gY6lIdSKKROkvte4="
  [mod."github.com/gdamore/tcell"]
    version = "v1.4.0"
    hash = "sha256-j39qlSHelGqkI7yHEAiG++Vur7IKL0sQZxStT+Q8EJ0="
  [mod."github.com/google/shlex"]
    version = "v0.0.0-20191202100458-e7afc7fbc510"
    hash = "sha256-1f392pCmS7AXVKXIC1SvKlYtK/rvW47F5CCkGT2G6JM="
  [mod."github.com/lucasb-eyer/go-colorful"]
    version = "v1.0.3"
    hash = "sha256-ychjhaR7EjjMvo2d61Bp0z2pb0zPnT5eiFOs1Zv5b4k="
  [mod."github.com/mattn/go-runewidth"]
    version = "v0.0.7"
    hash = "sha256-xsD47McW9Iq5jwmsefZBaKAbUG1GYDsJgeLvYWZF2eo="
  [mod."golang.org/x/sync"]
    version = "v0.1.0"
    hash = "sha256-Hygjq9euZ0qz6TvHYQwOZEjNiTbTh1nSLRAWZ6KFGR8="
  [mod."golang.org/x/sys"]
    version = "v0.0.0-20190626150813-e07cf5db2756"
    hash = "sha256-a5cRDZB15dSZlEWGcVUe3KDFqQcuqEzvNQtfymF8KVY="
  [mod."golang.org/x/text"]
    version = "v0.3.0"
    hash = "sha256-0FFbaxF1ZuAQF3sCcA85e8MO6prFeHint36inija4NY="
